name: 05 - 1 - Event Filters and Activity Types
on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu_latest
        steps:
            - run: echo "Running whenever a PR is opened or synchronizes AND base branch is main"

#adicionando filtros pra atividade ser verdadeira