name: 05 - 1 - Event Filters and Activity Types
on:
    pull_request:
        types:
            - closed
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu_latest
        steps:
            - run: echo "Running whenever a PR is closed"

#adicionando filtros pra atividade ser verdadeira
#criando outro fluxo de trabalho