name: 08 - Using Variables

on:
  push:
  workflow_dispatch:

env:
    WORKFLOW_VAR: "I'm a workflow env var"
    OVERWRITTEN: "I'm will be overwritten"


jobs:
  echo:
    runs-on: ubuntu-latest
    env:
        JOB_VAR: "I'm a job env var"
        OVERWRITTEN: "I have been overwritten ate the job level"

    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: 'I am a step env var'
          step-var2: 'I am another step env var'
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var 2: $step_var2"
          echo "Job env var 2: ${{ env.JOB_VAR }}"
          echo "Workflow env var 2: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten: ${{ env.OVERWRITTEN }}"
      - name: Overwrite job variable
        env:
            OVERWRITTEN: "I have been overwritten ate the step level"
        run: |
          echo "Step env var: ${{ env.OVERWRITTEN }}"
